# Site settings
title: Digital Avenue IT
description: A Comprihensive DevOps Guide
baseurl: "" # the subpath of your site, e.g. /blog
url: "digitalave.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: welcome.jpg
hero-title: Welcome to Digital Avenue
hero-description: A Comprehensive DevOps Guide 

# Author - Creator
author-name: Dimuthu Daundasekara
author-image: /pages/dimuthu.jpg
about-author: My name is Dimuthu Daundasekara. I turn coffie into code.
author-email: digitalavenuelk@gmail.com
author-twitter: https://twitter.com/DigitalAvenue2
author-facebook: https://www.facebook.com/digitalavenuelk
author-instagram: https://www.instagram.com/dimuit86/
author-youtube: https://www.youtube.com/channel/UCovlVsoRVItner26ZJPBjmQ?sub_confirmation=1
author-medium: https://medium.com/@dimuit86
#author-pinterest: https://pinterest.com/

# Other Authors - here you can add Other authors. For example Natali_Braxton
authors:
  dimuthu_daundasekara:
    author-name: Dimuthu Daundasekara
    author-image: dimuthu.jpg
    about-author: My name is Natali Braxton. I love walking, I play the guitar in my spare time. And also write articles about different technologies.
    author-email: natali.example@gmail.com
    author-twitter: https://twitter.com/dimuit86
    author-facebook: https://twitter.com/
    author-instagram: https://www.instagram.com/dimuit86/
    author-youtube: https://www.youtube.com/channel/UCovlVsoRVItner26ZJPBjmQ?sub_confirmation=1
    author-medium: https://medium.com/@dimuit86
    #author-pinterest: https://pinterest.com/

# Social Media Links (Links are located in hero and footer)
twitter: https://twitter.com/DigitalAvenue2
facebook: https://www.facebook.com/digitalavenuelk
#google-plus: https://plus.google.com/
instagram: https://www.instagram.com/dimuit86/
#pinterest: https://pinterest.com/
youtube: https://www.youtube.com/channel/UCovlVsoRVItner26ZJPBjmQ?sub_confirmation=1
medium: https://medium.com/@dimuit86

# Contact Form Settings
contact-subtitle: How can I help you?

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: https://github.us7.list-manage.com/subscribe?u=456a82ed7f789305670542cec&id=5ff5852b27 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: https-digitalave-github-io # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
