name: Digital Avenue IT
title: Digital Avenue IT | Verified DevOps Tutorials For Docker Kubernetes Azure Amazon Jenkins and System Administrator Tutorials
description: Digital Avenue IT Verified DevOps IT Admin Tutorials For Kubernetes, Azure, Jenkins, Docker, Linux, PfSense, Git, AWS and more. Learn DevOps Now.
tags:
  - DevOps
  - Digital Avenue
  - Tutorial
  - IT
  - Kubernete
  - Azure
  - Amazon
  - Jenkins
  - Docker
  - HowTo
  - DevOps Tutorials
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
#disqus_username: disqus_username
#paginate: 12